service: serverless-aws

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3005

functions:
  hello:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
